# !tyml @cargo/Cargo
[workspace]
resolver = "2"
members = [
    "src/light-nix",
    "src/light-nix-parser",
    "src/light-nix-grammar",
    "src/light-nix-name-resolver",
    "src/light-nix-dependency-graph",
    "src/light-nix-evaluator",
    "src/light-nix-ir",
    "src/light-nix-solver",
    "src/light-nix-type-checker"
]
