[package]
name = "light-nix"
version = "0.1.0"
edition = "2024"

[dependencies]
light-nix-parser = { path = "../light-nix-parser", version = "0.1.0" }
light-nix-name-resolver = { path = "../light-nix-name-resolver", version = "0.1.0" }
light-nix-dependency-graph = { path = "../light-nix-dependency-graph", version = "0.1.0" }
light-nix-evaluator = { path = "../light-nix-evaluator", version = "0.1.0" }
light-nix-ir = { path = "../light-nix-ir", version = "0.1.0" }
light-nix-solver = { path = "../light-nix-solver", version = "0.1.0" }
light-nix-type-checker = { path = "../light-nix-type-checker", version = "0.1.0" }
