[package]
name = "light-nix-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
light-nix-ir = { path = "../light-nix-ir", version = "0.1.0" }
light-nix-name-resolver = { path = "../light-nix-name-resolver", version = "0.1.0" }
light-nix-type-checker = { path = "../light-nix-type-checker", version = "0.1.0" }
z3 = "0.20.2"

[dev-dependencies]
light-nix-name-resolver = { path = "../light-nix-name-resolver", version = "0.1.0" }
light-nix-parser = { path = "../light-nix-parser", version = "0.1.0" }
